import { describe, it, expect, beforeAll, afterAll } from "vitest";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import { execSync } from "child_process";

/**
 * Real CLI execution tests.
 * These tests execute the compiled pookoo binary against a temporary
 * fixture directory to verify end-to-end behavior.
 */

const CLI_PATH = path.resolve(__dirname, "../../dist/index.js");

// Create a realistic fixture with a .env containing secrets and source code
function createFixture(): string {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "pookoo-cli-test-"));

  // Real .env with secrets (must NEVER leak into output)
  fs.writeFileSync(
    path.join(tmpDir, ".env"),
    [
      "DATABASE_URL=postgres://admin:s3cretP@ss@prod.db.example.com:5432/myapp",
      "STRIPE_SECRET_KEY=dummy_live_51SMMJBI92XLV9f6YRealProductionKey",
      "NEXT_PUBLIC_API_URL=https://api.example.com",
      "JWT_SECRET=super-secret-jwt-signing-key-do-not-share"
    ].join("\n"),
    "utf-8"
  );

  // Source file referencing variables
  fs.mkdirSync(path.join(tmpDir, "src"), { recursive: true });
  fs.writeFileSync(
    path.join(tmpDir, "src", "server.ts"),
    [
      'const dbUrl = process.env.DATABASE_URL || "postgres://localhost:5432/dev";',
      "const port = process.env.PORT || 3000;",
      "const apiUrl = process.env.NEXT_PUBLIC_API_URL;"
    ].join("\n"),
    "utf-8"
  );

  // package.json so it looks like a real project
  fs.writeFileSync(
    path.join(tmpDir, "package.json"),
    JSON.stringify({ name: "test-project", version: "1.0.0" }),
    "utf-8"
  );

  return tmpDir;
}

function cleanupFixture(dir: string): void {
  fs.rmSync(dir, { recursive: true, force: true });
}

describe("CLI execution: pookoo init", () => {
  let fixtureDir: string;

  beforeAll(() => {
    fixtureDir = createFixture();
  });

  afterAll(() => {
    cleanupFixture(fixtureDir);
  });

  it("writes .env.example inside the target directory by default", () => {
    const outputFile = path.join(fixtureDir, ".env.example");
    // Ensure clean state
    if (fs.existsSync(outputFile)) fs.unlinkSync(outputFile);

    execSync(`node "${CLI_PATH}" init "${fixtureDir}"`, {
      encoding: "utf-8",
      timeout: 30000
    });

    expect(fs.existsSync(outputFile)).toBe(true);
    const content = fs.readFileSync(outputFile, "utf-8");
    expect(content).toContain("DATABASE_URL=");
    expect(content).toContain("Auto-generated by Pookoo");
  });

  it("SAFETY: generated .env.example never contains real secret values", () => {
    const outputFile = path.join(fixtureDir, ".env.example");
    if (fs.existsSync(outputFile)) fs.unlinkSync(outputFile);

    execSync(`node "${CLI_PATH}" init "${fixtureDir}"`, {
      encoding: "utf-8",
      timeout: 30000
    });

    const content = fs.readFileSync(outputFile, "utf-8");

    // Real secrets from .env must NEVER appear
    expect(content).not.toContain("s3cretP@ss");
    expect(content).not.toContain("dummy_live_51SMMJBI92XLV9f6YRealProductionKey");
    expect(content).not.toContain("super-secret-jwt-signing-key-do-not-share");
    expect(content).not.toContain("postgres://admin");

    // Keys must still be present as blank assignments
    expect(content).toContain("DATABASE_URL=");
    expect(content).toContain("STRIPE_SECRET_KEY=");
  });

  it("refuses to overwrite existing file without --force", () => {
    const outputFile = path.join(fixtureDir, ".env.example");
    // Ensure file exists from previous test
    if (!fs.existsSync(outputFile)) {
      fs.writeFileSync(outputFile, "existing content", "utf-8");
    }

    let exitCode = 0;
    try {
      execSync(`node "${CLI_PATH}" init "${fixtureDir}"`, {
        encoding: "utf-8",
        timeout: 30000,
        stdio: "pipe"
      });
    } catch (err) {
      exitCode = (err as { status: number }).status;
    }

    expect(exitCode).toBe(1);
  });

  it("overwrites existing file with --force", () => {
    const outputFile = path.join(fixtureDir, ".env.example");
    fs.writeFileSync(outputFile, "old content", "utf-8");

    execSync(`node "${CLI_PATH}" init "${fixtureDir}" --force`, {
      encoding: "utf-8",
      timeout: 30000
    });

    const content = fs.readFileSync(outputFile, "utf-8");
    expect(content).not.toBe("old content");
    expect(content).toContain("Auto-generated by Pookoo");
  });
});

describe("CLI execution: pookoo docs", () => {
  let fixtureDir: string;

  beforeAll(() => {
    fixtureDir = createFixture();
  });

  afterAll(() => {
    cleanupFixture(fixtureDir);
  });

  it("writes CONFIG_DOCS.md inside the target directory by default", () => {
    const outputFile = path.join(fixtureDir, "CONFIG_DOCS.md");
    if (fs.existsSync(outputFile)) fs.unlinkSync(outputFile);

    execSync(`node "${CLI_PATH}" docs "${fixtureDir}"`, {
      encoding: "utf-8",
      timeout: 30000
    });

    expect(fs.existsSync(outputFile)).toBe(true);
    const content = fs.readFileSync(outputFile, "utf-8");
    expect(content).toContain("# Configuration Reference");
  });

  it("SAFETY: generated docs never contain real secret values", () => {
    const outputFile = path.join(fixtureDir, "CONFIG_DOCS.md");
    if (fs.existsSync(outputFile)) fs.unlinkSync(outputFile);

    execSync(`node "${CLI_PATH}" docs "${fixtureDir}" --force`, {
      encoding: "utf-8",
      timeout: 30000
    });

    const content = fs.readFileSync(outputFile, "utf-8");
    expect(content).not.toContain("s3cretP@ss");
    expect(content).not.toContain("dummy_live_");
    expect(content).not.toContain("super-secret-jwt-signing-key");
  });

  it("refuses to overwrite existing file without --force", () => {
    const outputFile = path.join(fixtureDir, "CONFIG_DOCS.md");
    if (!fs.existsSync(outputFile)) {
      fs.writeFileSync(outputFile, "existing", "utf-8");
    }

    let exitCode = 0;
    try {
      execSync(`node "${CLI_PATH}" docs "${fixtureDir}"`, {
        encoding: "utf-8",
        timeout: 30000,
        stdio: "pipe"
      });
    } catch (err) {
      exitCode = (err as { status: number }).status;
    }

    expect(exitCode).toBe(1);
  });

  it("output is deterministic across runs", () => {
    const out1 = path.join(fixtureDir, "docs_run1.md");
    const out2 = path.join(fixtureDir, "docs_run2.md");

    execSync(`node "${CLI_PATH}" docs "${fixtureDir}" -o docs_run1.md --force`, {
      encoding: "utf-8",
      timeout: 30000
    });
    execSync(`node "${CLI_PATH}" docs "${fixtureDir}" -o docs_run2.md --force`, {
      encoding: "utf-8",
      timeout: 30000
    });

    const content1 = fs.readFileSync(out1, "utf-8");
    const content2 = fs.readFileSync(out2, "utf-8");
    expect(content1).toBe(content2);
  });
});
