import { ScanResult } from "@pookoo/shared";

export interface EnvGeneratorOptions {
  /** Add comments from rawComment or inferred SDK descriptions. Default: true */
  includeDescriptions?: boolean;
  /** Add "# Used in: file.ts:12" comments showing where each variable is consumed. Default: true */
  includeSourceHints?: boolean;
  /** Group variables by framework/SDK prefix (e.g., Clerk, Stripe, Database). Default: true */
  groupByCategory?: boolean;
  /** Group variables by the directory that declares them (monorepo-aware). Overrides groupByCategory. Default: false */
  groupByDirectory?: boolean;
  /** Add placeholder example values like "your-api-key-here". Default: false */
  includeExampleValues?: boolean;
}

interface EnvVariable {
  key: string;
  defaultValue?: string;
  comment?: string;
  usedInFiles: string[];
  declaredInFiles: string[];
  category: string;
  isPublic: boolean;
}

/**
 * Categorizes a variable key into a human-readable group name.
 * Uses prefix matching against well-known SDK patterns.
 */
function categorizeVariable(key: string): string {
  const upperKey = key.toUpperCase();

  // Strip framework public prefixes for categorization
  const stripped = upperKey
    .replace(/^NEXT_PUBLIC_/, "")
    .replace(/^VITE_/, "")
    .replace(/^REACT_APP_/, "");

  const categories: [RegExp, string][] = [
    [/^CLERK_/, "Authentication (Clerk)"],
    [/^STRIPE_/, "Payments (Stripe)"],
    [/^FIREBASE_/, "Firebase"],
    [/^SUPABASE_/, "Database (Supabase)"],
    [/^AUTH0_/, "Authentication (Auth0)"],
    [/^NEXTAUTH_/, "Authentication (NextAuth)"],
    [/^SENTRY_/, "Error Tracking (Sentry)"],
    [/^GOOGLE_MAPS/, "Maps (Google)"],
    [/^GOOGLE_ANALYTICS|^GA_|^GTM_/, "Analytics (Google)"],
    [/^GOOGLE_/, "Google"],
    [/^MONGODB|^MONGO_/, "Database (MongoDB)"],
    [/^POSTGRES|^PG_|^DATABASE_URL/, "Database (PostgreSQL)"],
    [/^REDIS_|^UPSTASH_/, "Database (Redis)"],
    [/^AWS_/, "Cloud (AWS)"],
    [/^AZURE_/, "Cloud (Azure)"],
    [/^VERCEL_/, "Deployment (Vercel)"],
    [/^SENDGRID_|^POSTMARK_|^RESEND_/, "Email"],
    [/^TWILIO_/, "SMS (Twilio)"],
    [/^PUSHER_/, "Realtime (Pusher)"],
    [/^ALGOLIA_/, "Search (Algolia)"],
    [/^CLOUDINARY_/, "Media (Cloudinary)"],
    [/^MAPBOX_/, "Maps (Mapbox)"],
    [/^MIXPANEL_|^POSTHOG_|^SEGMENT_|^AMPLITUDE_/, "Analytics"],
    [/^UPLOADTHING_/, "File Upload (UploadThing)"],
    [/^S3_|^BUCKET_/, "Storage (S3)"],
    [/^SMTP_|^MAIL_|^EMAIL_/, "Email"],
    [/^JWT_|^SESSION_/, "Security"],
    [/^LOG_|^DEBUG/, "Logging"],
    [/^PORT$|^HOST$|^HOSTNAME$/, "Server"],
    [/^NODE_/, "Node.js"]
  ];

  for (const [pattern, category] of categories) {
    if (pattern.test(stripped)) {
      return category;
    }
  }

  // Check the original key too (before stripping)
  if (/DB_|DATABASE/.test(upperKey)) return "Database";
  if (/API_URL|API_KEY|API_SECRET/.test(upperKey)) return "API";
  if (/SECRET|PASSWORD|PRIVATE/.test(upperKey)) return "Security";

  return "General";
}

/**
 * Generates a `.env.example` file from scan results.
 *
 * Collects all declared configuration items and all consumed-but-undeclared
 * variables from the knowledge graph, then produces a well-organized
 * `.env.example` with descriptions, source hints, and framework grouping.
 */
export function generateEnvExample(result: ScanResult, options: EnvGeneratorOptions = {}): string {
  const {
    includeDescriptions = true,
    includeSourceHints = true,
    groupByCategory = true,
    groupByDirectory = false,
    includeExampleValues = false
  } = options;

  const variables = collectVariables(result);
  const lines: string[] = [];

  lines.push("# ════════════════════════════════════════════════════════════════");
  lines.push("# Environment Variables");
  lines.push(`# Auto-generated by Pookoo · ${variables.length} variables discovered`);
  lines.push("# ════════════════════════════════════════════════════════════════");
  lines.push("");

  if (groupByDirectory) {
    const sections = groupVariablesByDirectory(variables);

    for (const section of sections) {
      lines.push(`# ─────────────────────────────────────`);
      lines.push(`# → ${section.title}`);
      lines.push(`# ─────────────────────────────────────`);
      lines.push("");

      if (section.undeclaredSubGroups) {
        for (const [dir, vars] of [...section.undeclaredSubGroups.entries()].sort()) {
          const sortedVars = [...vars].sort((a, b) => a.key.localeCompare(b.key));
          if (dir !== "") {
            lines.push(`# ${displayDirectory(dir)}`);
          }
          for (const v of sortedVars) {
            appendVariable(lines, v, {
              includeDescriptions,
              includeSourceHints,
              includeExampleValues,
              includeDeclaredIn: true
            });
          }
          lines.push("");
        }
      } else if (section.variables) {
        const sortedVars = [...section.variables].sort((a, b) => a.key.localeCompare(b.key));
        for (const v of sortedVars) {
          appendVariable(lines, v, {
            includeDescriptions,
            includeSourceHints,
            includeExampleValues,
            includeDeclaredIn: true
          });
        }
        lines.push("");
      }
    }
  } else if (groupByCategory) {
    const grouped = groupVariablesByCategory(variables);
    const categoryOrder = Array.from(grouped.keys()).sort();

    for (const category of categoryOrder) {
      const vars = grouped.get(category)!;
      lines.push(`# ─────────────────────────────────────`);
      lines.push(`# ${category}`);
      lines.push(`# ─────────────────────────────────────`);
      lines.push("");

      for (const v of vars) {
        appendVariable(lines, v, {
          includeDescriptions,
          includeSourceHints,
          includeExampleValues,
          includeDeclaredIn: false
        });
      }

      lines.push("");
    }
  } else {
    const sorted = [...variables].sort((a, b) => a.key.localeCompare(b.key));
    for (const v of sorted) {
      appendVariable(lines, v, {
        includeDescriptions,
        includeSourceHints,
        includeExampleValues,
        includeDeclaredIn: false
      });
    }
  }

  return lines.join("\n").trimEnd() + "\n";
}

function collectVariables(result: ScanResult): EnvVariable[] {
  const variableMap = new Map<string, EnvVariable>();
  const { nodes, edges } = result.knowledgeGraph;

  // Map each variable to every file that declares it via DECLARES edges.
  // .env.example files are templates, not real declarations, so they are excluded.
  const declaredByConfig = new Map<string, string[]>();
  for (const edge of edges) {
    if (edge.kind !== "DECLARES") continue;
    const sourceMatch = /^file:(.+)$/.exec(edge.sourceId);
    const targetMatch = /^config:(.+)$/.exec(edge.targetId);
    if (!sourceMatch || !targetMatch) continue;
    const filePath = sourceMatch[1];
    if (filePath.includes(".env.example")) continue;
    const key = targetMatch[1];
    const list = declaredByConfig.get(key) || [];
    if (!list.includes(filePath)) list.push(filePath);
    declaredByConfig.set(key, list);
  }

  const collectDeclaredIn = (key: string, primaryFile?: string): string[] => {
    const all = new Set(declaredByConfig.get(key) || []);
    if (primaryFile && !primaryFile.includes(".env.example")) all.add(primaryFile);
    return [...all].sort();
  };

  // Collect declared configuration items
  const configNodes = nodes.filter((n) => n.kind === "ConfigurationItem");
  for (const node of configNodes) {
    const key = node.label;
    const meta = node.metadata;
    const loc = meta.sourceLocation as { filePath?: string } | undefined;
    variableMap.set(key, {
      key,
      defaultValue: meta.defaultValue as string | undefined,
      comment: meta.rawComment as string | undefined,
      usedInFiles: [],
      declaredInFiles: collectDeclaredIn(key, loc?.filePath),
      category: categorizeVariable(key),
      isPublic: /^(NEXT_PUBLIC_|VITE_|REACT_APP_)/.test(key)
    });
  }

  // Collect usage locations for each variable
  const callSiteNodes = nodes.filter((n) => n.kind === "CallSite");
  for (const callSite of callSiteNodes) {
    const itemKey = callSite.metadata.itemKey as string | undefined;
    if (!itemKey || itemKey === "<DYNAMIC_COMPUTED>") continue;

    const loc = callSite.metadata.sourceLocation as
      { filePath: string; lineNumber: number } | undefined;
    if (!loc) continue;

    const fileRef = `${loc.filePath}:${loc.lineNumber}`;
    const existing = variableMap.get(itemKey);
    if (existing) {
      if (!existing.usedInFiles.includes(fileRef)) {
        existing.usedInFiles.push(fileRef);
      }
    } else {
      // Variable consumed in source but never declared in any .env file
      variableMap.set(itemKey, {
        key: itemKey,
        defaultValue: undefined,
        comment: undefined,
        usedInFiles: [fileRef],
        declaredInFiles: collectDeclaredIn(itemKey),
        category: categorizeVariable(itemKey),
        isPublic: /^(NEXT_PUBLIC_|VITE_|REACT_APP_)/.test(itemKey)
      });
    }
  }

  return Array.from(variableMap.values());
}

function groupVariablesByCategory(variables: EnvVariable[]): Map<string, EnvVariable[]> {
  const grouped = new Map<string, EnvVariable[]>();
  for (const v of variables) {
    const list = grouped.get(v.category) || [];
    list.push(v);
    grouped.set(v.category, list);
  }

  // Sort variables within each category alphabetically
  for (const [, vars] of grouped) {
    vars.sort((a, b) => a.key.localeCompare(b.key));
  }

  return grouped;
}

interface DirectorySection {
  title: string;
  variables?: EnvVariable[];
  undeclaredSubGroups?: Map<string, EnvVariable[]>;
}

/** Returns the parent directory of a relative file path, or "." for root-level files. */
function directoryOfFile(filePath: string): string {
  const idx = filePath.lastIndexOf("/");
  if (idx < 0) return ".";
  return filePath.slice(0, idx);
}

function displayDirectory(dir: string): string {
  return dir === "." ? "./" : `${dir}/`;
}

/** Strips the ":line" suffix from a usage file reference and returns its directory. */
function usageDirectory(fileRef: string): string {
  return directoryOfFile(fileRef.replace(/:\d+$/, ""));
}

/** Directory containing the most call-sites for a variable, as a usage-based fallback. */
function dominantUsageDirectory(v: EnvVariable): string {
  const counts = new Map<string, number>();
  for (const ref of v.usedInFiles) {
    const dir = usageDirectory(ref);
    counts.set(dir, (counts.get(dir) || 0) + 1);
  }

  let best = "";
  let bestCount = 0;
  for (const [dir, count] of counts) {
    if (count > bestCount || (count === bestCount && (best === "" || dir < best))) {
      best = dir;
      bestCount = count;
    }
  }

  return best;
}

/**
 * Groups variables by the directory that declares them.
 * - A variable appears under EVERY directory that declares it, so each
 *   directory section is the complete list of that directory's variables.
 * - Variables never declared (consumed in code only) -> an "Undeclared" section,
 *   sub-grouped by their dominant usage directory.
 */
function groupVariablesByDirectory(variables: EnvVariable[]): DirectorySection[] {
  const declared = new Map<string, EnvVariable[]>();
  const undeclared: EnvVariable[] = [];

  for (const v of variables) {
    const dirs = [...new Set(v.declaredInFiles.map(directoryOfFile))];
    if (dirs.length === 0) {
      undeclared.push(v);
    } else {
      for (const dir of dirs) {
        const list = declared.get(dir) || [];
        list.push(v);
        declared.set(dir, list);
      }
    }
  }

  const sections: DirectorySection[] = [];
  for (const dir of [...declared.keys()].sort()) {
    sections.push({ title: displayDirectory(dir), variables: declared.get(dir)! });
  }
  if (undeclared.length > 0) {
    const subGroups = new Map<string, EnvVariable[]>();
    for (const v of undeclared) {
      const dir = dominantUsageDirectory(v);
      const list = subGroups.get(dir) || [];
      list.push(v);
      subGroups.set(dir, list);
    }
    sections.push({
      title: "Undeclared (referenced in code, no .env declaration)",
      undeclaredSubGroups: subGroups
    });
  }

  return sections;
}

/**
 * True when a comment line contains an actual environment value rather than
 * documentation. Commented-out assignments and URIs with embedded credentials
 * must never be rendered into the exportable `.env.example`.
 */
function looksLikeEnvValue(commentLine: string): boolean {
  const line = commentLine.trim();
  if (/^[A-Za-z_][A-Za-z0-9_]*=/.test(line)) return true;
  if (/[a-zA-Z][a-zA-Z0-9+.-]*:\/\/[^\s]+:[^\s@]+@/.test(line)) return true;
  return false;
}

function appendVariable(
  lines: string[],
  v: EnvVariable,
  opts: {
    includeDescriptions: boolean;
    includeSourceHints: boolean;
    includeExampleValues: boolean;
    includeDeclaredIn: boolean;
  }
): void {
  if (opts.includeDescriptions && v.comment) {
    const cleaned = v.comment.replace(/^#\s*/, "").trim();
    if (cleaned) {
      const commentLines = cleaned.split("\n");
      for (const cl of commentLines) {
        const line = cl.trim().replace(/^#+\s*/, "");
        // Safety: comment lines that carry actual values (commented-out
        // assignments, URIs with credentials) must never reach the exportable
        // .env.example. They leak real secrets and don't describe the variable.
        if (looksLikeEnvValue(line)) continue;
        lines.push(`# ${line}`);
      }
    }
  }

  if (opts.includeDeclaredIn && v.declaredInFiles.length > 0) {
    lines.push(`# Declared in: ${v.declaredInFiles.join(", ")}`);
  }

  if (opts.includeSourceHints && v.usedInFiles.length > 0) {
    const maxShown = 3;
    const deduped = [...new Set(v.usedInFiles)];
    const shown = deduped.slice(0, maxShown);
    const remaining = deduped.length - maxShown;
    const suffix = remaining > 0 ? ` (+${remaining} more)` : "";
    lines.push(`# Used in: ${shown.join(", ")}${suffix}`);
  }

  let value = "";
  if (opts.includeExampleValues) {
    value = inferPlaceholder(v.key);
  }

  lines.push(`${v.key}=${value}`);
}

function inferPlaceholder(key: string): string {
  const upperKey = key.toUpperCase();

  // Specific patterns first (before generic URL/URI catch-all)
  if (upperKey.includes("MONGODB") || upperKey.includes("MONGO_"))
    return "mongodb://localhost:27017/myapp";
  if (upperKey.includes("SENTRY") && upperKey.includes("DSN")) {
    return "https://example@sentry.io/12345";
  }
  if (upperKey.includes("DATABASE_URL")) return "postgres://user:password@localhost:5432/dbname";
  // Generic patterns
  if (upperKey.includes("URL") || upperKey.includes("URI")) return "https://example.com";
  if (upperKey.includes("PORT")) return "3000";
  if (upperKey.includes("HOST")) return "localhost";
  if (upperKey.includes("EMAIL")) return "user@example.com";
  if (upperKey.includes("PASSWORD")) return "your-password-here";
  if (upperKey.includes("SECRET")) return "your-secret-here";
  if (upperKey.includes("KEY")) return "your-key-here";
  if (upperKey.includes("TOKEN")) return "your-token-here";

  return "";
}
