import { ScanResult } from "@pookoo/shared";

export interface EnvGeneratorOptions {
  /** Add comments from rawComment or inferred SDK descriptions. Default: true */
  includeDescriptions?: boolean;
  /** Add "# Used in: file.ts:12" comments showing where each variable is consumed. Default: true */
  includeSourceHints?: boolean;
  /** Group variables by framework/SDK prefix (e.g., Clerk, Stripe, Database). Default: true */
  groupByCategory?: boolean;
  /** Add placeholder example values like "your-api-key-here". Default: false */
  includeExampleValues?: boolean;
}

interface EnvVariable {
  key: string;
  defaultValue?: string;
  comment?: string;
  usedInFiles: string[];
  category: string;
  isPublic: boolean;
}

/**
 * Categorizes a variable key into a human-readable group name.
 * Uses prefix matching against well-known SDK patterns.
 */
function categorizeVariable(key: string): string {
  const upperKey = key.toUpperCase();

  // Strip framework public prefixes for categorization
  const stripped = upperKey
    .replace(/^NEXT_PUBLIC_/, "")
    .replace(/^VITE_/, "")
    .replace(/^REACT_APP_/, "");

  const categories: [RegExp, string][] = [
    [/^CLERK_/, "Authentication (Clerk)"],
    [/^STRIPE_/, "Payments (Stripe)"],
    [/^FIREBASE_/, "Firebase"],
    [/^SUPABASE_/, "Database (Supabase)"],
    [/^AUTH0_/, "Authentication (Auth0)"],
    [/^NEXTAUTH_/, "Authentication (NextAuth)"],
    [/^SENTRY_/, "Error Tracking (Sentry)"],
    [/^GOOGLE_MAPS/, "Maps (Google)"],
    [/^GOOGLE_ANALYTICS|^GA_|^GTM_/, "Analytics (Google)"],
    [/^GOOGLE_/, "Google"],
    [/^MONGODB|^MONGO_/, "Database (MongoDB)"],
    [/^POSTGRES|^PG_|^DATABASE_URL/, "Database (PostgreSQL)"],
    [/^REDIS_|^UPSTASH_/, "Database (Redis)"],
    [/^AWS_/, "Cloud (AWS)"],
    [/^AZURE_/, "Cloud (Azure)"],
    [/^VERCEL_/, "Deployment (Vercel)"],
    [/^SENDGRID_|^POSTMARK_|^RESEND_/, "Email"],
    [/^TWILIO_/, "SMS (Twilio)"],
    [/^PUSHER_/, "Realtime (Pusher)"],
    [/^ALGOLIA_/, "Search (Algolia)"],
    [/^CLOUDINARY_/, "Media (Cloudinary)"],
    [/^MAPBOX_/, "Maps (Mapbox)"],
    [/^MIXPANEL_|^POSTHOG_|^SEGMENT_|^AMPLITUDE_/, "Analytics"],
    [/^UPLOADTHING_/, "File Upload (UploadThing)"],
    [/^S3_|^BUCKET_/, "Storage (S3)"],
    [/^SMTP_|^MAIL_|^EMAIL_/, "Email"],
    [/^JWT_|^SESSION_/, "Security"],
    [/^LOG_|^DEBUG/, "Logging"],
    [/^PORT$|^HOST$|^HOSTNAME$/, "Server"],
    [/^NODE_/, "Node.js"]
  ];

  for (const [pattern, category] of categories) {
    if (pattern.test(stripped)) {
      return category;
    }
  }

  // Check the original key too (before stripping)
  if (/DB_|DATABASE/.test(upperKey)) return "Database";
  if (/API_URL|API_KEY|API_SECRET/.test(upperKey)) return "API";
  if (/SECRET|PASSWORD|PRIVATE/.test(upperKey)) return "Security";

  return "General";
}

/**
 * Generates a `.env.example` file from scan results.
 *
 * Collects all declared configuration items and all consumed-but-undeclared
 * variables from the knowledge graph, then produces a well-organized
 * `.env.example` with descriptions, source hints, and framework grouping.
 */
export function generateEnvExample(result: ScanResult, options: EnvGeneratorOptions = {}): string {
  const {
    includeDescriptions = true,
    includeSourceHints = true,
    groupByCategory = true,
    includeExampleValues = false
  } = options;

  const variables = collectVariables(result);
  const lines: string[] = [];

  lines.push("# ════════════════════════════════════════════════════════════════");
  lines.push("# Environment Variables");
  lines.push(`# Auto-generated by Pookoo · ${variables.length} variables discovered`);
  lines.push("# ════════════════════════════════════════════════════════════════");
  lines.push("");

  if (groupByCategory) {
    const grouped = groupVariablesByCategory(variables);
    const categoryOrder = Array.from(grouped.keys()).sort();

    for (const category of categoryOrder) {
      const vars = grouped.get(category)!;
      lines.push(`# ──────────────────────────────────────`);
      lines.push(`# ${category}`);
      lines.push(`# ──────────────────────────────────────`);
      lines.push("");

      for (const v of vars) {
        appendVariable(lines, v, { includeDescriptions, includeSourceHints, includeExampleValues });
      }

      lines.push("");
    }
  } else {
    const sorted = [...variables].sort((a, b) => a.key.localeCompare(b.key));
    for (const v of sorted) {
      appendVariable(lines, v, { includeDescriptions, includeSourceHints, includeExampleValues });
    }
  }

  return lines.join("\n").trimEnd() + "\n";
}

function collectVariables(result: ScanResult): EnvVariable[] {
  const variableMap = new Map<string, EnvVariable>();
  const { nodes } = result.knowledgeGraph;

  // Collect declared configuration items
  const configNodes = nodes.filter((n) => n.kind === "ConfigurationItem");
  for (const node of configNodes) {
    const key = node.label;
    const meta = node.metadata;
    variableMap.set(key, {
      key,
      defaultValue: meta.defaultValue as string | undefined,
      comment: meta.rawComment as string | undefined,
      usedInFiles: [],
      category: categorizeVariable(key),
      isPublic: /^(NEXT_PUBLIC_|VITE_|REACT_APP_)/.test(key)
    });
  }

  // Collect usage locations for each variable
  const callSiteNodes = nodes.filter((n) => n.kind === "CallSite");
  for (const callSite of callSiteNodes) {
    const itemKey = callSite.metadata.itemKey as string | undefined;
    if (!itemKey || itemKey === "<DYNAMIC_COMPUTED>") continue;

    const loc = callSite.metadata.sourceLocation as
      { filePath: string; lineNumber: number } | undefined;
    if (!loc) continue;

    const existing = variableMap.get(itemKey);
    if (existing) {
      const fileRef = `${loc.filePath}:${loc.lineNumber}`;
      if (!existing.usedInFiles.includes(fileRef)) {
        existing.usedInFiles.push(fileRef);
      }
    } else {
      // Variable consumed in source but never declared in any .env file
      const fileRef = `${loc.filePath}:${loc.lineNumber}`;
      variableMap.set(itemKey, {
        key: itemKey,
        defaultValue: undefined,
        comment: undefined,
        usedInFiles: [fileRef],
        category: categorizeVariable(itemKey),
        isPublic: /^(NEXT_PUBLIC_|VITE_|REACT_APP_)/.test(itemKey)
      });
    }
  }

  return Array.from(variableMap.values());
}

function groupVariablesByCategory(variables: EnvVariable[]): Map<string, EnvVariable[]> {
  const grouped = new Map<string, EnvVariable[]>();
  for (const v of variables) {
    const list = grouped.get(v.category) || [];
    list.push(v);
    grouped.set(v.category, list);
  }

  // Sort variables within each category alphabetically
  for (const [, vars] of grouped) {
    vars.sort((a, b) => a.key.localeCompare(b.key));
  }

  return grouped;
}

function appendVariable(
  lines: string[],
  v: EnvVariable,
  opts: { includeDescriptions: boolean; includeSourceHints: boolean; includeExampleValues: boolean }
): void {
  if (opts.includeDescriptions && v.comment) {
    const cleaned = v.comment.replace(/^#\s*/, "").trim();
    if (cleaned) {
      const commentLines = cleaned.split("\n");
      for (const cl of commentLines) {
        lines.push(`# ${cl}`);
      }
    }
  }

  if (opts.includeSourceHints && v.usedInFiles.length > 0) {
    const maxShown = 3;
    const deduped = [...new Set(v.usedInFiles)];
    const shown = deduped.slice(0, maxShown);
    const remaining = deduped.length - maxShown;
    const suffix = remaining > 0 ? ` (+${remaining} more)` : "";
    lines.push(`# Used in: ${shown.join(", ")}${suffix}`);
  }

  let value = "";
  if (opts.includeExampleValues) {
    value = inferPlaceholder(v.key);
  }

  lines.push(`${v.key}=${value}`);
}

function inferPlaceholder(key: string): string {
  const upperKey = key.toUpperCase();

  // Specific patterns first (before generic URL/URI catch-all)
  if (upperKey.includes("MONGODB") || upperKey.includes("MONGO_"))
    return "mongodb://localhost:27017/myapp";
  if (upperKey.includes("SENTRY") && upperKey.includes("DSN")) {
    return "https://example@sentry.io/12345";
  }
  if (upperKey.includes("DATABASE_URL")) return "postgres://user:password@localhost:5432/dbname";
  // Generic patterns
  if (upperKey.includes("URL") || upperKey.includes("URI")) return "https://example.com";
  if (upperKey.includes("PORT")) return "3000";
  if (upperKey.includes("HOST")) return "localhost";
  if (upperKey.includes("EMAIL")) return "user@example.com";
  if (upperKey.includes("PASSWORD")) return "your-password-here";
  if (upperKey.includes("SECRET")) return "your-secret-here";
  if (upperKey.includes("KEY")) return "your-key-here";
  if (upperKey.includes("TOKEN")) return "your-token-here";

  return "";
}
