import { ScanResult } from "@pookoo/shared";

export interface DocsGeneratorOptions {
  /** Title for the documentation. Default: "Configuration Reference" */
  title?: string;
  /** Include a variable relationship summary. Default: true */
  includeSummary?: boolean;
}

interface DocVariable {
  key: string;
  required: boolean;
  defaultValue?: string;
  description?: string;
  scope: "Client" | "Server" | "Both";
  usedIn: string[];
  declaredIn: string[];
  framework?: string;
  category: string;
}

/**
 * Categorizes a variable key into a human-readable group name.
 */
function categorizeForDocs(key: string): string {
  const upperKey = key.toUpperCase();

  const stripped = upperKey
    .replace(/^NEXT_PUBLIC_/, "")
    .replace(/^VITE_/, "")
    .replace(/^REACT_APP_/, "");

  const categories: [RegExp, string][] = [
    [/^CLERK_/, "Authentication (Clerk)"],
    [/^STRIPE_/, "Payments (Stripe)"],
    [/^FIREBASE_/, "Firebase"],
    [/^SUPABASE_/, "Database (Supabase)"],
    [/^AUTH0_/, "Authentication (Auth0)"],
    [/^NEXTAUTH_/, "Authentication (NextAuth)"],
    [/^SENTRY_/, "Error Tracking (Sentry)"],
    [/^GOOGLE_MAPS/, "Maps (Google)"],
    [/^GOOGLE_ANALYTICS|^GA_|^GTM_/, "Analytics (Google)"],
    [/^GOOGLE_/, "Google"],
    [/^MONGODB|^MONGO_/, "Database (MongoDB)"],
    [/^POSTGRES|^PG_|^DATABASE_URL/, "Database (PostgreSQL)"],
    [/^REDIS_|^UPSTASH_/, "Database (Redis)"],
    [/^AWS_/, "Cloud (AWS)"],
    [/^AZURE_/, "Cloud (Azure)"],
    [/^VERCEL_/, "Deployment (Vercel)"],
    [/^SENDGRID_|^POSTMARK_|^RESEND_/, "Email"],
    [/^TWILIO_/, "SMS (Twilio)"],
    [/^PUSHER_/, "Realtime (Pusher)"],
    [/^ALGOLIA_/, "Search (Algolia)"],
    [/^CLOUDINARY_/, "Media (Cloudinary)"],
    [/^MAPBOX_/, "Maps (Mapbox)"],
    [/^MIXPANEL_|^POSTHOG_|^SEGMENT_|^AMPLITUDE_/, "Analytics"],
    [/^UPLOADTHING_/, "File Upload (UploadThing)"],
    [/^S3_|^BUCKET_/, "Storage (S3)"],
    [/^SMTP_|^MAIL_|^EMAIL_/, "Email"],
    [/^JWT_|^SESSION_/, "Security"],
    [/^LOG_|^DEBUG/, "Logging"],
    [/^PORT$|^HOST$|^HOSTNAME$/, "Server"],
    [/^NODE_/, "Node.js"],
  ];

  for (const [pattern, category] of categories) {
    if (pattern.test(stripped)) {
      return category;
    }
  }

  if (/DB_|DATABASE/.test(upperKey)) return "Database";
  if (/API_URL|API_KEY|API_SECRET/.test(upperKey)) return "API";
  if (/SECRET|PASSWORD|PRIVATE/.test(upperKey)) return "Security";

  return "General";
}

function determineScope(key: string): "Client" | "Server" {
  if (/^(NEXT_PUBLIC_|VITE_|REACT_APP_)/.test(key)) {
    return "Client";
  }
  return "Server";
}

/**
 * Generates a markdown configuration reference document from scan results.
 *
 * Produces a well-structured markdown document with tables showing every
 * variable, its scope, defaults, and usage locations — suitable for
 * README inclusion or standalone documentation.
 */
export function generateConfigDocs(
  result: ScanResult,
  options: DocsGeneratorOptions = {}
): { content: string; count: number } {
  const {
    title = "Configuration Reference",
    includeSummary = true,
  } = options;

  const variables = collectDocVariables(result);
  const lines: string[] = [];

  // Header
  lines.push(`# ${title}`);
  lines.push("");
  lines.push(`> Auto-generated by [Pookoo](https://github.com/CreatorLZ/pookoo). ${variables.length} variables discovered across ${result.scannedFilesCount} files.`);
  lines.push("");

  // Summary stats
  if (includeSummary) {
    const clientVars = variables.filter((v) => v.scope === "Client");
    const serverVars = variables.filter((v) => v.scope === "Server");
    const requiredVars = variables.filter((v) => v.required);

    lines.push("## Overview");
    lines.push("");
    lines.push(`| Metric | Count |`);
    lines.push(`| :--- | :--- |`);
    lines.push(`| Total Variables | ${variables.length} |`);
    lines.push(`| Server-only | ${serverVars.length} |`);
    lines.push(`| Client-exposed | ${clientVars.length} |`);
    lines.push(`| Required | ${requiredVars.length} |`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  // Group by category
  const grouped = new Map<string, DocVariable[]>();
  for (const v of variables) {
    const list = grouped.get(v.category) || [];
    list.push(v);
    grouped.set(v.category, list);
  }

  const categoryOrder = Array.from(grouped.keys()).sort();

  for (const category of categoryOrder) {
    const vars = grouped.get(category)!;
    vars.sort((a, b) => a.key.localeCompare(b.key));

    lines.push(`## ${category}`);
    lines.push("");
    lines.push("| Variable | Required | Scope | Used In |");
    lines.push("| :--- | :---: | :---: | :--- |");

    for (const v of vars) {
      const required = v.required ? "✓" : "—";
      const scope = v.scope === "Client" ? "🌐 Client" : "🔒 Server";
      const usedIn = v.usedIn.length > 0
        ? v.usedIn.slice(0, 3).map((f) => extractFilename(f)).join(", ") +
          (v.usedIn.length > 3 ? ` (+${v.usedIn.length - 3})` : "")
        : "—";

      lines.push(`| \`${v.key}\` | ${required} | ${scope} | ${usedIn} |`);
    }

    lines.push("");
  }

  // Findings summary if there are issues
  if (result.findings.length > 0) {
    lines.push("---");
    lines.push("");
    lines.push("## Issues Found");
    lines.push("");
    const issueWord = result.findings.length === 1 ? "issue" : "issues";
    lines.push(`Pookoo detected **${result.findings.length}** configuration ${issueWord}.`);
    lines.push("");

    const bySeverity: Record<string, number> = {};
    for (const f of result.findings) {
      bySeverity[f.severity] = (bySeverity[f.severity] || 0) + 1;
    }

    lines.push("| Severity | Count |");
    lines.push("| :--- | :--- |");
    for (const sev of ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]) {
      if (bySeverity[sev]) {
        lines.push(`| ${sev} | ${bySeverity[sev]} |`);
      }
    }
    lines.push("");
    lines.push("Run `pookoo scan` for detailed findings and remediation advice.");
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(`*Generated by Pookoo v0.1.0*`);
  lines.push("");

  return { content: lines.join("\n"), count: variables.length };
}

function collectDocVariables(result: ScanResult): DocVariable[] {
  const variableMap = new Map<string, DocVariable>();
  const { nodes } = result.knowledgeGraph;

  // Collect declared configuration items
  const configNodes = nodes.filter((n) => n.kind === "ConfigurationItem");
  for (const node of configNodes) {
    const key = node.label;
    const meta = node.metadata;
    const loc = meta.sourceLocation as { filePath: string } | undefined;

    variableMap.set(key, {
      key,
      required: (meta.isRequired as boolean) || false,
      defaultValue: meta.defaultValue as string | undefined,
      description: meta.rawComment as string | undefined,
      scope: determineScope(key),
      usedIn: [],
      declaredIn: loc ? [loc.filePath] : [],
      framework: meta.inferredFramework as string | undefined,
      category: categorizeForDocs(key),
    });
  }

  // Collect usage locations
  const callSiteNodes = nodes.filter((n) => n.kind === "CallSite");
  for (const callSite of callSiteNodes) {
    const itemKey = callSite.metadata.itemKey as string | undefined;
    if (!itemKey || itemKey === "<DYNAMIC_COMPUTED>") continue;

    const loc = callSite.metadata.sourceLocation as { filePath: string; lineNumber: number } | undefined;
    if (!loc) continue;

    const existing = variableMap.get(itemKey);
    if (existing) {
      const fileRef = `${loc.filePath}:${loc.lineNumber}`;
      if (!existing.usedIn.includes(fileRef)) {
        existing.usedIn.push(fileRef);
      }
    } else {
      const fileRef = `${loc.filePath}:${loc.lineNumber}`;
      variableMap.set(itemKey, {
        key: itemKey,
        required: false,
        defaultValue: undefined,
        description: undefined,
        scope: determineScope(itemKey),
        usedIn: [fileRef],
        declaredIn: [],
        framework: undefined,
        category: categorizeForDocs(itemKey),
      });
    }
  }

  return Array.from(variableMap.values());
}


function extractFilename(fileRef: string): string {
  // "src/server/db.ts:5" → "db.ts"
  const parts = fileRef.split("/");
  const last = parts[parts.length - 1];
  // Remove line number for display
  return last.split(":")[0];
}
