import { describe, it, expect } from "vitest";
import { discoverConfigurationItems } from "../index";
import { VirtualFile } from "../../loader/walker";

describe("discoverConfigurationItems", () => {
  it("discovers configuration items from .env and container files", () => {
    const files: VirtualFile[] = [
      {
        path: ".env",
        relativePath: ".env",
        content: "PORT=3000\nNEXT_PUBLIC_API_URL=https://api.example.com",
        fileType: "ENV"
      },
      {
        path: "docker-compose.yml",
        relativePath: "docker-compose.yml",
        content: "services:\n  app:\n    environment:\n      - DATABASE_URL=postgres://db:5432",
        fileType: "CONTAINER"
      }
    ];

    const frameworks = [
      {
        id: "nextjs",
        name: "Next.js",
        publicPrefixes: ["NEXT_PUBLIC_"],
        implicitEnvFiles: [".env"]
      }
    ];

    const items = discoverConfigurationItems(files, frameworks);

    expect(items).toHaveLength(3);
    const keys = items.map((i) => i.key);
    expect(keys).toContain("PORT");
    expect(keys).toContain("NEXT_PUBLIC_API_URL");
    expect(keys).toContain("DATABASE_URL");

    const nextPublicItem = items.find((i) => i.key === "NEXT_PUBLIC_API_URL");
    expect(nextPublicItem?.inferredFramework).toBe("Next.js");
  });

  it("keeps user-authored lines while filtering generated markers from .env.example comments", () => {
    const files: VirtualFile[] = [
      {
        path: ".env",
        relativePath: ".env",
        content: "STRIPE_KEY=",
        fileType: "ENV"
      },
      {
        path: ".env.example",
        relativePath: ".env.example",
        content:
          "# This API key is used for Stripe payments\n" +
          "# Declared in: .env\n" +
          "# Used in: src/billing.ts:1\n" +
          "STRIPE_KEY=",
        fileType: "ENV"
      }
    ];

    const items = discoverConfigurationItems(files);
    const item = items.find((i) => i.key === "STRIPE_KEY");
    expect(item?.rawComment).toBe("This API key is used for Stripe payments");
  });

  it("does not merge purely synthetic .env.example comments", () => {
    const files: VirtualFile[] = [
      {
        path: ".env",
        relativePath: ".env",
        content: "MONGODB_URI=",
        fileType: "ENV"
      },
      {
        path: ".env.example",
        relativePath: ".env.example",
        content: "# Declared in: .env\nMONGODB_URI=",
        fileType: "ENV"
      }
    ];

    const items = discoverConfigurationItems(files);
    const item = items.find((i) => i.key === "MONGODB_URI");
    expect(item?.rawComment).toBeUndefined();
  });

  it("filters generated header and section marker lines individually", () => {
    const files: VirtualFile[] = [
      {
        path: ".env",
        relativePath: ".env",
        content: "JWT_SECRET=",
        fileType: "ENV"
      },
      {
        path: ".env.example",
        relativePath: ".env.example",
        content:
          "# Auto-generated by Pookoo\n" +
          "# → ./\n" +
          "# ────────────────\n" +
          "# JWT signing key\n" +
          "JWT_SECRET=",
        fileType: "ENV"
      }
    ];

    const items = discoverConfigurationItems(files);
    const item = items.find((i) => i.key === "JWT_SECRET");
    expect(item?.rawComment).toBe("JWT signing key");
  });
});
