import { describe, it, expect } from "vitest";
import { generateEnvExample } from "../index";
import { ScanResult, KnowledgeGraphData } from "@pookoo/shared";

function makeScanResult(graph: KnowledgeGraphData): ScanResult {
  return {
    knowledgeGraph: graph,
    findings: [],
    healthScore: 100,
    scannedFilesCount: 10
  };
}

describe("generateEnvExample", () => {
  it("generates env example from configuration items", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:DATABASE_URL",
          kind: "ConfigurationItem",
          label: "DATABASE_URL",
          metadata: { isRequired: true, rawComment: "PostgreSQL connection string" }
        },
        {
          id: "config:PORT",
          kind: "ConfigurationItem",
          label: "PORT",
          metadata: { isRequired: false, defaultValue: "3000" }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result);
    expect(output).toContain("DATABASE_URL=");
    // defaultValue must NOT appear in output — safety invariant
    expect(output).not.toContain("3000");
    expect(output).toContain("PORT=");
    expect(output).toContain("PostgreSQL connection string");
    expect(output).toContain("Auto-generated by Pookoo");
  });

  it("groups variables by category when enabled", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:CLERK_SECRET_KEY",
          kind: "ConfigurationItem",
          label: "CLERK_SECRET_KEY",
          metadata: {}
        },
        {
          id: "config:STRIPE_PUBLISHABLE_KEY",
          kind: "ConfigurationItem",
          label: "STRIPE_PUBLISHABLE_KEY",
          metadata: {}
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result, { groupByCategory: true });
    expect(output).toContain("Authentication (Clerk)");
    expect(output).toContain("Payments (Stripe)");
  });

  it("includes source file usage hints", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:DATABASE_URL",
          kind: "ConfigurationItem",
          label: "DATABASE_URL",
          metadata: {}
        },
        {
          id: "callsite:1",
          kind: "CallSite",
          label: "DATABASE_URL (DIRECT_MEMBER)",
          metadata: {
            itemKey: "DATABASE_URL",
            callType: "DIRECT_MEMBER",
            sourceLocation: { filePath: "src/db.ts", lineNumber: 5 }
          }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result, { includeSourceHints: true });
    expect(output).toContain("# Used in: src/db.ts:5");
  });

  it("discovers variables from call-sites that have no declaration", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "callsite:1",
          kind: "CallSite",
          label: "UNDECLARED_VAR (DIRECT_MEMBER)",
          metadata: {
            itemKey: "UNDECLARED_VAR",
            callType: "DIRECT_MEMBER",
            sourceLocation: { filePath: "src/config.ts", lineNumber: 10 }
          }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result);
    expect(output).toContain("UNDECLARED_VAR=");
  });

  it("skips dynamic computed call-sites", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "callsite:1",
          kind: "CallSite",
          label: "<DYNAMIC_COMPUTED>",
          metadata: {
            itemKey: "<DYNAMIC_COMPUTED>",
            callType: "DYNAMIC_COMPUTED",
            sourceLocation: { filePath: "src/util.ts", lineNumber: 3 }
          }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result);
    expect(output).not.toContain("DYNAMIC_COMPUTED");
  });

  it("includes placeholder values when enabled", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:API_URL",
          kind: "ConfigurationItem",
          label: "API_URL",
          metadata: {}
        },
        {
          id: "config:JWT_SECRET",
          kind: "ConfigurationItem",
          label: "JWT_SECRET",
          metadata: {}
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result, { includeExampleValues: true });
    expect(output).toContain("API_URL=https://example.com");
    expect(output).toContain("JWT_SECRET=your-secret-here");
  });

  it("omits descriptions when disabled", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:DATABASE_URL",
          kind: "ConfigurationItem",
          label: "DATABASE_URL",
          metadata: { rawComment: "PostgreSQL connection string" }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result, { includeDescriptions: false });
    expect(output).not.toContain("PostgreSQL connection string");
    expect(output).toContain("DATABASE_URL=");
  });

  it("omits source hints when disabled", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:PORT",
          kind: "ConfigurationItem",
          label: "PORT",
          metadata: {}
        },
        {
          id: "callsite:1",
          kind: "CallSite",
          label: "PORT (DIRECT_MEMBER)",
          metadata: {
            itemKey: "PORT",
            callType: "DIRECT_MEMBER",
            sourceLocation: { filePath: "src/server.ts", lineNumber: 5 }
          }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result, { includeSourceHints: false });
    expect(output).not.toContain("# Used in:");
  });

  it("SAFETY: never exports real .env values into generated output", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:STRIPE_SECRET_KEY",
          kind: "ConfigurationItem",
          label: "STRIPE_SECRET_KEY",
          metadata: {
            isRequired: true,
            defaultValue: "dummy_test_51SMMJBI92XLV9f6YYM92L0o0ifuvQy"
          }
        },
        {
          id: "config:MONGODB_URI",
          kind: "ConfigurationItem",
          label: "MONGODB_URI",
          metadata: {
            isRequired: true,
            defaultValue: "mongodb+srv://realuser:realpass@cluster.mongodb.net/db"
          }
        },
        {
          id: "config:CLERK_SECRET_KEY",
          kind: "ConfigurationItem",
          label: "CLERK_SECRET_KEY",
          metadata: {
            isRequired: true,
            defaultValue: "dummy_test_gvkAZQYvZ1gsn8mnGKJErNV9aKpJCwPOtC0uj5vQDz"
          }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result);

    // Real secret values must NEVER appear
    expect(output).not.toContain("dummy_test_51SMMJBI92XLV9f6YYM92L0o0ifuvQy");
    expect(output).not.toContain("mongodb+srv://realuser:realpass");
    expect(output).not.toContain("dummy_test_gvkAZQYvZ1gsn8mnGKJErNV9aKpJCwPOtC0uj5vQDz");

    // Keys must still appear as blank assignments
    expect(output).toContain("STRIPE_SECRET_KEY=");
    expect(output).toContain("MONGODB_URI=");
    expect(output).toContain("CLERK_SECRET_KEY=");

    // Even with --examples, only safe placeholders appear
    const outputWithExamples = generateEnvExample(result, { includeExampleValues: true });
    expect(outputWithExamples).not.toContain("dummy_test_");
    expect(outputWithExamples).not.toContain("mongodb+srv://");
    expect(outputWithExamples).toContain("STRIPE_SECRET_KEY=your-secret-here");
    // MONGODB_URI now correctly matches the MongoDB-specific placeholder (before generic URL/URI)
    expect(outputWithExamples).toContain("MONGODB_URI=mongodb://localhost:27017/myapp");
  });

  it("SAFETY: strips commented-out secret values from description comments", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:LOG_SALT",
          kind: "ConfigurationItem",
          label: "LOG_SALT",
          metadata: {
            isRequired: true,
            rawComment:
              "# bagxtra starts here\n" +
              "# NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_Y29ycmVjdA\n" +
              "# CLERK_SECRET_KEY=sk_test_CyiO1RBnykcXaQ1ioEqKxIcC88EfAW6f5L1KI5bufK\n" +
              "# MONGODB_URI=mongodb+srv://bagxtrateam_db_user:1e8scntfkgeRDbXo@host/db\n" +
              "# Reasonable doc line\n"
          }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result, { includeDescriptions: true });

    // Real secret values must NEVER appear, even when they live in comments
    expect(output).not.toContain("pk_test_Y29ycmVjdA");
    expect(output).not.toContain("sk_test_CyiO1RBnykcXaQ1ioEqKxIcC88EfAW6f5L1KI5bufK");
    expect(output).not.toContain("bagxtrateam_db_user");
    expect(output).not.toContain("1e8scntfkgeRDbXo");
    // The bagxtra marker line and the doc line are legitimate comments and stay
    expect(output).toContain("# bagxtra starts here");
    expect(output).toContain("# Reasonable doc line");
    expect(output).toContain("LOG_SALT=");
  });

  it("groups variables by declaring directory when enabled", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:DATABASE_URL",
          kind: "ConfigurationItem",
          label: "DATABASE_URL",
          metadata: {
            sourceLocation: { filePath: "apps/api/.env", lineNumber: 1, columnRange: [0, 12] }
          }
        },
        {
          id: "config:PORT",
          kind: "ConfigurationItem",
          label: "PORT",
          metadata: { sourceLocation: { filePath: ".env", lineNumber: 1, columnRange: [0, 4] } }
        }
      ],
      edges: [
        { id: "e1", sourceId: "file:apps/api/.env", targetId: "config:DATABASE_URL", kind: "DECLARES" },
        { id: "e2", sourceId: "file:.env", targetId: "config:PORT", kind: "DECLARES" }
      ]
    });

    const output = generateEnvExample(result, { groupByDirectory: true });
    expect(output).toContain("# → apps/api/");
    expect(output).toContain("# → ./");
    expect(output).toContain("# Declared in: apps/api/.env");
    expect(output).toContain("# Declared in: .env");
  });

  it("lists variables declared in multiple files under every declaring directory", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:CORS_ORIGIN",
          kind: "ConfigurationItem",
          label: "CORS_ORIGIN",
          metadata: { sourceLocation: { filePath: ".env", lineNumber: 1, columnRange: [0, 11] } }
        }
      ],
      edges: [
        { id: "e1", sourceId: "file:.env", targetId: "config:CORS_ORIGIN", kind: "DECLARES" },
        { id: "e2", sourceId: "file:apps/api/.env", targetId: "config:CORS_ORIGIN", kind: "DECLARES" }
      ]
    });

    const output = generateEnvExample(result, { groupByDirectory: true });
    // Must appear under BOTH directories so each section is a complete list
    expect(output).toContain("# → ./");
    expect(output).toContain("# → apps/api/");
    expect(output).toContain("# Declared in: .env, apps/api/.env");
    // A multi-dir variable must not be pulled out of its directories' sections
    expect(output).not.toContain("Shared (declared in multiple directories)");
  });

  it("groups consumed-but-undeclared variables by dominant usage directory", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "callsite:1",
          kind: "CallSite",
          label: "FEATURE_FLAG_X (DIRECT_MEMBER)",
          metadata: {
            itemKey: "FEATURE_FLAG_X",
            callType: "DIRECT_MEMBER",
            sourceLocation: { filePath: "apps/web/src/analytics.ts", lineNumber: 20 }
          }
        },
        {
          id: "callsite:2",
          kind: "CallSite",
          label: "FEATURE_FLAG_X (DIRECT_MEMBER)",
          metadata: {
            itemKey: "FEATURE_FLAG_X",
            callType: "DIRECT_MEMBER",
            sourceLocation: { filePath: "apps/web/src/app.ts", lineNumber: 8 }
          }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result, { groupByDirectory: true });
    expect(output).toContain("# → Undeclared (referenced in code, no .env declaration)");
    expect(output).toContain("# apps/web/src/");
    expect(output).toContain("FEATURE_FLAG_X=");
  });

  it("ignores .env.example files when determining declaration directories", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:API_KEY",
          kind: "ConfigurationItem",
          label: "API_KEY",
          metadata: { sourceLocation: { filePath: "apps/api/.env", lineNumber: 1, columnRange: [0, 7] } }
        }
      ],
      edges: [
        { id: "e1", sourceId: "file:.env.example", targetId: "config:API_KEY", kind: "DECLARES" },
        { id: "e2", sourceId: "file:apps/api/.env", targetId: "config:API_KEY", kind: "DECLARES" }
      ]
    });

    const output = generateEnvExample(result, { groupByDirectory: true });
    expect(output).toContain("# → apps/api/");
    expect(output).not.toContain(".env.example");
    expect(output).toContain("# Declared in: apps/api/.env");
  });

  it("directory grouping takes precedence over category grouping", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:CLERK_SECRET_KEY",
          kind: "ConfigurationItem",
          label: "CLERK_SECRET_KEY",
          metadata: { sourceLocation: { filePath: "apps/api/.env", lineNumber: 1, columnRange: [0, 16] } }
        }
      ],
      edges: [
        { id: "e1", sourceId: "file:apps/api/.env", targetId: "config:CLERK_SECRET_KEY", kind: "DECLARES" }
      ]
    });

    const output = generateEnvExample(result, { groupByDirectory: true, groupByCategory: true });
    expect(output).toContain("# → apps/api/");
    expect(output).not.toContain("Authentication (Clerk)");
  });

  it("does not add declared-in hints unless directory grouping is enabled", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:DATABASE_URL",
          kind: "ConfigurationItem",
          label: "DATABASE_URL",
          metadata: { sourceLocation: { filePath: "apps/api/.env", lineNumber: 1, columnRange: [0, 12] } }
        }
      ],
      edges: [
        { id: "e1", sourceId: "file:apps/api/.env", targetId: "config:DATABASE_URL", kind: "DECLARES" }
      ]
    });

    const output = generateEnvExample(result);
    expect(output).not.toContain("# Declared in:");
    expect(output).not.toContain("# → ");
    expect(output).toContain("DATABASE_URL=");
  });

  it("handles variables with neither declaration nor usage without a bogus directory marker", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:ORPHAN_VAR",
          kind: "ConfigurationItem",
          label: "ORPHAN_VAR",
          metadata: {}
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result, { groupByDirectory: true });
    expect(output).toContain("# → Undeclared (referenced in code, no .env declaration)");
    expect(output).toContain("ORPHAN_VAR=");
    expect(output).not.toContain("# /");
  });
});
