import { describe, it, expect } from "vitest";
import { generateEnvExample } from "../index";
import { ScanResult, KnowledgeGraphData } from "@pookoo/shared";

function makeScanResult(graph: KnowledgeGraphData): ScanResult {
  return {
    knowledgeGraph: graph,
    findings: [],
    healthScore: 100,
    scannedFilesCount: 10
  };
}

describe("generateEnvExample", () => {
  it("generates env example from configuration items", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:DATABASE_URL",
          kind: "ConfigurationItem",
          label: "DATABASE_URL",
          metadata: { isRequired: true, rawComment: "PostgreSQL connection string" }
        },
        {
          id: "config:PORT",
          kind: "ConfigurationItem",
          label: "PORT",
          metadata: { isRequired: false, defaultValue: "3000" }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result);
    expect(output).toContain("DATABASE_URL=");
    // defaultValue must NOT appear in output — safety invariant
    expect(output).not.toContain("3000");
    expect(output).toContain("PORT=");
    expect(output).toContain("PostgreSQL connection string");
    expect(output).toContain("Auto-generated by Pookoo");
  });

  it("groups variables by category when enabled", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:CLERK_SECRET_KEY",
          kind: "ConfigurationItem",
          label: "CLERK_SECRET_KEY",
          metadata: {}
        },
        {
          id: "config:STRIPE_PUBLISHABLE_KEY",
          kind: "ConfigurationItem",
          label: "STRIPE_PUBLISHABLE_KEY",
          metadata: {}
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result, { groupByCategory: true });
    expect(output).toContain("Authentication (Clerk)");
    expect(output).toContain("Payments (Stripe)");
  });

  it("includes source file usage hints", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:DATABASE_URL",
          kind: "ConfigurationItem",
          label: "DATABASE_URL",
          metadata: {}
        },
        {
          id: "callsite:1",
          kind: "CallSite",
          label: "DATABASE_URL (DIRECT_MEMBER)",
          metadata: {
            itemKey: "DATABASE_URL",
            callType: "DIRECT_MEMBER",
            sourceLocation: { filePath: "src/db.ts", lineNumber: 5 }
          }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result, { includeSourceHints: true });
    expect(output).toContain("# Used in: src/db.ts:5");
  });

  it("discovers variables from call-sites that have no declaration", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "callsite:1",
          kind: "CallSite",
          label: "UNDECLARED_VAR (DIRECT_MEMBER)",
          metadata: {
            itemKey: "UNDECLARED_VAR",
            callType: "DIRECT_MEMBER",
            sourceLocation: { filePath: "src/config.ts", lineNumber: 10 }
          }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result);
    expect(output).toContain("UNDECLARED_VAR=");
  });

  it("skips dynamic computed call-sites", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "callsite:1",
          kind: "CallSite",
          label: "<DYNAMIC_COMPUTED>",
          metadata: {
            itemKey: "<DYNAMIC_COMPUTED>",
            callType: "DYNAMIC_COMPUTED",
            sourceLocation: { filePath: "src/util.ts", lineNumber: 3 }
          }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result);
    expect(output).not.toContain("DYNAMIC_COMPUTED");
  });

  it("includes placeholder values when enabled", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:API_URL",
          kind: "ConfigurationItem",
          label: "API_URL",
          metadata: {}
        },
        {
          id: "config:JWT_SECRET",
          kind: "ConfigurationItem",
          label: "JWT_SECRET",
          metadata: {}
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result, { includeExampleValues: true });
    expect(output).toContain("API_URL=https://example.com");
    expect(output).toContain("JWT_SECRET=your-secret-here");
  });

  it("omits descriptions when disabled", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:DATABASE_URL",
          kind: "ConfigurationItem",
          label: "DATABASE_URL",
          metadata: { rawComment: "PostgreSQL connection string" }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result, { includeDescriptions: false });
    expect(output).not.toContain("PostgreSQL connection string");
    expect(output).toContain("DATABASE_URL=");
  });

  it("omits source hints when disabled", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:PORT",
          kind: "ConfigurationItem",
          label: "PORT",
          metadata: {}
        },
        {
          id: "callsite:1",
          kind: "CallSite",
          label: "PORT (DIRECT_MEMBER)",
          metadata: {
            itemKey: "PORT",
            callType: "DIRECT_MEMBER",
            sourceLocation: { filePath: "src/server.ts", lineNumber: 5 }
          }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result, { includeSourceHints: false });
    expect(output).not.toContain("# Used in:");
  });

  it("SAFETY: never exports real .env values into generated output", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:STRIPE_SECRET_KEY",
          kind: "ConfigurationItem",
          label: "STRIPE_SECRET_KEY",
          metadata: {
            isRequired: true,
            defaultValue: "dummy_test_51SMMJBI92XLV9f6YYM92L0o0ifuvQy"
          }
        },
        {
          id: "config:MONGODB_URI",
          kind: "ConfigurationItem",
          label: "MONGODB_URI",
          metadata: {
            isRequired: true,
            defaultValue: "mongodb+srv://realuser:realpass@cluster.mongodb.net/db"
          }
        },
        {
          id: "config:CLERK_SECRET_KEY",
          kind: "ConfigurationItem",
          label: "CLERK_SECRET_KEY",
          metadata: {
            isRequired: true,
            defaultValue: "dummy_test_gvkAZQYvZ1gsn8mnGKJErNV9aKpJCwPOtC0uj5vQDz"
          }
        }
      ],
      edges: []
    });

    const output = generateEnvExample(result);

    // Real secret values must NEVER appear
    expect(output).not.toContain("dummy_test_51SMMJBI92XLV9f6YYM92L0o0ifuvQy");
    expect(output).not.toContain("mongodb+srv://realuser:realpass");
    expect(output).not.toContain("dummy_test_gvkAZQYvZ1gsn8mnGKJErNV9aKpJCwPOtC0uj5vQDz");

    // Keys must still appear as blank assignments
    expect(output).toContain("STRIPE_SECRET_KEY=");
    expect(output).toContain("MONGODB_URI=");
    expect(output).toContain("CLERK_SECRET_KEY=");

    // Even with --examples, only safe placeholders appear
    const outputWithExamples = generateEnvExample(result, { includeExampleValues: true });
    expect(outputWithExamples).not.toContain("dummy_test_");
    expect(outputWithExamples).not.toContain("mongodb+srv://");
    expect(outputWithExamples).toContain("STRIPE_SECRET_KEY=your-secret-here");
    // MONGODB_URI now correctly matches the MongoDB-specific placeholder (before generic URL/URI)
    expect(outputWithExamples).toContain("MONGODB_URI=mongodb://localhost:27017/myapp");
  });
});
