import { describe, it, expect } from "vitest";
import { generateConfigDocs } from "../index";
import { ScanResult, KnowledgeGraphData } from "@pookoo/shared";

function makeScanResult(graph: KnowledgeGraphData, overrides?: Partial<ScanResult>): ScanResult {
  return {
    knowledgeGraph: graph,
    findings: [],
    healthScore: 100,
    scannedFilesCount: 10,
    ...overrides
  };
}

describe("generateConfigDocs", () => {
  it("generates a markdown document with variable tables", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:DATABASE_URL",
          kind: "ConfigurationItem",
          label: "DATABASE_URL",
          metadata: { isRequired: true, defaultValue: "mongodb://localhost:27017/myapp" }
        },
        {
          id: "config:PORT",
          kind: "ConfigurationItem",
          label: "PORT",
          metadata: { isRequired: false, defaultValue: "3000" }
        }
      ],
      edges: []
    });

    const { content: output } = generateConfigDocs(result);
    expect(output).toContain("# Configuration Reference");
    expect(output).toContain("Auto-generated by");
    expect(output).toContain("`DATABASE_URL`");
    expect(output).toContain("`PORT`");
    expect(output).toContain("✓"); // required marker
    // Default values must NOT appear in docs output — safety invariant
    expect(output).not.toContain("mongodb://localhost:27017/myapp");
    expect(output).not.toContain("3000");
  });

  it("categorizes variables into groups", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:CLERK_SECRET_KEY",
          kind: "ConfigurationItem",
          label: "CLERK_SECRET_KEY",
          metadata: { isRequired: true }
        },
        {
          id: "config:STRIPE_PUBLISHABLE_KEY",
          kind: "ConfigurationItem",
          label: "STRIPE_PUBLISHABLE_KEY",
          metadata: {}
        }
      ],
      edges: []
    });

    const { content: output } = generateConfigDocs(result);
    expect(output).toContain("## Authentication (Clerk)");
    expect(output).toContain("## Payments (Stripe)");
  });

  it("shows client vs server scope", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:NEXT_PUBLIC_API_URL",
          kind: "ConfigurationItem",
          label: "NEXT_PUBLIC_API_URL",
          metadata: {}
        },
        {
          id: "config:DATABASE_URL",
          kind: "ConfigurationItem",
          label: "DATABASE_URL",
          metadata: {}
        }
      ],
      edges: []
    });

    const { content: output } = generateConfigDocs(result);
    expect(output).toContain("🌐 Client");
    expect(output).toContain("🔒 Server");
  });

  it("includes overview summary with counts", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:NEXT_PUBLIC_KEY",
          kind: "ConfigurationItem",
          label: "NEXT_PUBLIC_KEY",
          metadata: { isRequired: true }
        },
        {
          id: "config:SECRET",
          kind: "ConfigurationItem",
          label: "SECRET",
          metadata: { isRequired: true }
        }
      ],
      edges: []
    });

    const { content: output } = generateConfigDocs(result);
    expect(output).toContain("## Overview");
    expect(output).toContain("Total Variables | 2");
    expect(output).toContain("Client-exposed | 1");
    expect(output).toContain("Server-only | 1");
    expect(output).toContain("Required | 2");
  });

  it("includes issues summary when findings exist", () => {
    const result = makeScanResult(
      {
        nodes: [
          {
            id: "config:UNUSED",
            kind: "ConfigurationItem",
            label: "UNUSED",
            metadata: {}
          }
        ],
        edges: []
      },
      {
        findings: [
          {
            id: "finding:1",
            ruleId: "NO_STATIC_REFERENCE_FOUND",
            severity: "INFO",
            targetKey: "UNUSED",
            message: "test",
            explanation: "test",
            remediation: "test"
          }
        ],
        healthScore: 100
      }
    );

    const { content: output } = generateConfigDocs(result);
    expect(output).toContain("## Issues Found");
    expect(output).toContain("**1** configuration issue");
    expect(output).toContain("INFO | 1");
  });

  it("allows custom title", () => {
    const result = makeScanResult({ nodes: [], edges: [] });
    const { content: output } = generateConfigDocs(result, { title: "My App Config" });
    expect(output).toContain("# My App Config");
  });

  it("includes usage file references", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:PORT",
          kind: "ConfigurationItem",
          label: "PORT",
          metadata: {}
        },
        {
          id: "callsite:1",
          kind: "CallSite",
          label: "PORT (DIRECT_MEMBER)",
          metadata: {
            itemKey: "PORT",
            callType: "DIRECT_MEMBER",
            sourceLocation: { filePath: "src/server.ts", lineNumber: 5 }
          }
        }
      ],
      edges: []
    });

    const { content: output } = generateConfigDocs(result);
    expect(output).toContain("server.ts");
  });

  it("SAFETY: never renders real default values in generated docs", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:STRIPE_SECRET_KEY",
          kind: "ConfigurationItem",
          label: "STRIPE_SECRET_KEY",
          metadata: {
            isRequired: true,
            defaultValue: "dummy_test_51SMMJBI92XLV9f6YYM92L0o0ifuvQy"
          }
        },
        {
          id: "config:DATABASE_URL",
          kind: "ConfigurationItem",
          label: "DATABASE_URL",
          metadata: {
            defaultValue: "postgres://admin:secretpass@db.example.com:5432/prod"
          }
        }
      ],
      edges: []
    });

    const { content: output } = generateConfigDocs(result);
    expect(output).not.toContain("sk_test_");
    expect(output).not.toContain("secretpass");
    expect(output).not.toContain("postgres://admin");
    expect(output).toContain("`STRIPE_SECRET_KEY`");
    expect(output).toContain("`DATABASE_URL`");
  });

  it("output is deterministic across runs (no timestamp)", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:PORT",
          kind: "ConfigurationItem",
          label: "PORT",
          metadata: { isRequired: false }
        }
      ],
      edges: []
    });

    const { content: run1 } = generateConfigDocs(result);
    const { content: run2 } = generateConfigDocs(result);
    expect(run1).toBe(run2);
    expect(run1).not.toMatch(/Generated on \d{4}-\d{2}-\d{2}/);
    expect(run1).toContain("Generated by Pookoo");
  });

  it("does not include health score in generated docs", () => {
    const result = makeScanResult({
      nodes: [
        {
          id: "config:PORT",
          kind: "ConfigurationItem",
          label: "PORT",
          metadata: {}
        }
      ],
      edges: []
    });

    const { content: output } = generateConfigDocs(result);
    expect(output).not.toContain("Health Score");
    expect(output).not.toContain("/100");
  });
});
